
services:
  app:
    build:
      context: ../..
      dockerfile: .docker/images/php/Dockerfile
      target: dev
      args:
        BASE_IMAGE: php:8.2-apache
        GID: ${GID:-1000}
        UID: ${UID:-1000}
    ports:
      - "8080:80"
    volumes:
      - ../../app:/srv/app
      - ~/.gitconfig:/home/serveruser/.gitconfig
      - ~/.gitignore_global:/home/serveruser/.gitignore_global
      - ../images/php/config/apache/sites-available/000-default.conf:/etc/apache2/sites-available/000-default.conf
    environment:
      - APP_ENV=dev
      - APACHE_DOCUMENT_ROOT=/srv/app/public
#      - APACHE_RUN_USER="serveruser"
#      - APACHE_RUN_GROUP="serveruser"
    depends_on:
      - mysql
      - postgres

  mysql:
    image: mysql:8
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=app
      - MYSQL_USER=app
      - MYSQL_PASSWORD=app

  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=app


